name: Mamba_installation
channels:
  - conda-forge
dependencies:
  - python=3.10
  - nodejs
  - bokeh
  - numpy
  - pandas
  - xarray
  - astropy
  - cloudpickle
  - doit
  - entrypoints
  - dtale
  - ipywidgets
  - jupyterlab
  - widgetsnbextension
  - ipylab
  - Folium
  - branca
  - eemont
  - geeViz
  - bqplot
  - ipycanvas
  - ipyevents
  - ipyleaflet
  - mpld3
  - markupsafe
  - ipympl
  - ipydrawio
  - ipydrawio-widgets
  - ipydrawio-export
  - ipyradiant
  - ipyflex
  - IPySlides
  - jupyterlab_iframe
  - jupyterlab-lsp
  - dash-daq 
  - plotly
  - jupyterlab-fasta
  - jupyterlab-geojson
  - jupyterlab-bpmn
  - jupyterlab-dmn
  - jupyterlab-tour
  - jupyterlab-github
  - jupyterlab-citation-manager
  - jupyterlab-dash
  - jupyterlab-itables
  - jupyterlab-plugin-graph
  - jupyterlab-jitsi
  - jupyterlab-blockly
  - jupyter-simlin
  - jupyterlab-image-editor
  - jupyterlab-wav
  - jupyterlab-notifications
  - jupyterlab-execute-time
  - jupyterlab-empinken-extension
  - jupyterlab-filesystem-access
# ------------------------------------
  - jupyterthemes
  - theme-darcula
  - pip:
     - jupyter-core
     - jupyter-server
     - jupyterlab-widgets
     - geemap
     - autoplotter
     - kaleido
     - jupyterlab-autoplot
     - jupyterlab-skip-traceback
     - jupyterlab-stickyland
     - jupyterlab_comments
     - jupyterlite