name: Mamba_installation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - nodejs
  - bokeh
  - numpy
  - pandas
  - xarray
  - astropy
  - cloudpickle
  - doit
  - entrypoints
  - dtale
  - ipywidgets
  - jupyterlab
  - widgetsnbextension
  - ipylab
  - Folium
  - branca
  - eemont
  - bqplot
  - ipycanvas
  - ipyevents
  - ipyleaflet
  - mpld3
  - markupsafe
  - ipympl
  - ipydrawio
  - ipydrawio-widgets
  - ipydrawio-export
  - ipyradiant
  - ipyflex
  - IPySlides
  - jupyterlab_iframe
  - jupyterlab-lsp
  - dash-daq 
  - plotly
  - jupyterlab-fasta
  - jupyterlab-geojson
  - jupyterlab-tour
  - jupyterlab-github
  - jupyterlab-dash
  - jupyterlab-plugin-graph
  - jupyterlab-blockly
  - jupyterlab-notifications
  - jupyterlab-filesystem-access
  # ----- Reinstall some other packages ----
  - metakernel
  - calysto
# ------------------------------------
  - jupyterthemes
  - jupyterlab_miami_nights
  - theme-darcula
  - jupyterlab-fonts
# ------------------------------------
  - vispy
  - ipyx
  - ipybertin
# ------------------------------------
  - pip
  - pip:
     - jupyter-core
     - jupyter-server
     - jupyterlab-widgets
     - geemap
     - geeViz
     - autoplotter
     - kaleido
     - jupyterlab-autoplot
     - jupyterlab-skip-traceback
     - jupyterlab-stickyland
     - jupyterlab_comments
     - jupyterlab-bpmn
     - jupyterlab-dmn
     - jupyterlab-citation-manager
     - jupyterlab-itables
     - jupyterlab-jitsi
     - jupyter-simlin
     - jupyterlab-image-editor
     - jupyterlab-wav
     - jupyterlab-execute-time
     - jupyterlab-empinken-extension
     - aitk.keras
     - imjoy-jupyterlab-extension
     - dsvisualizer
     - statworx-theme
     - pyplot-themes
     - jltheme
     - jupyterlab-theme-hale
     - skillsnetwork-authoring-extension
     - pyotritonclient
     # ------------------------------------
     - wasm-spec-kernel
     - wasmpy
     - wasmpy-build
     - pywasm3
     - wasmtime
     - wasmer
     - wasmer-compiler-llvm
     - wasmer-compiler-cranelift
     - wasmer-compiler-singlepass
     - pyaswasm
     # ------------------------------------
     #- pyodide
     - matplotlib-pyodide
     - pyodide-html
     - pyodide-http
     - pyodide-build
     - exodide
     - micropip
     - build
     # ------------------------------------
     - jupyterlite
     # ------------------------------------
     - ipyp5
     - pygbag
     - Enpyre