name: Mamba_installation
channels:
  - conda-forge
dependencies:
  - python=3.10
  - bokeh
  - numpy
  - pandas
  - xarray
  - astropy
  - nodejs
  - cloudpickle
  - doit
  - entrypoints
  - dtale
  - ipywidgets
  - jupyterlab
  - widgetsnbextension~=4.0
  - ipylab
  - pip
  - pip:
     - jupyter-core
     - jupyter-server
     - jupyterlab-widgets