name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-env: true
          cache-downloads: true
          environment-file: Environment.yml
          environment-name: noEnv
          #extra-specs: |
          #  python=3.9
      - name: Run Python to check if microMamba or 
        shell: bash -l {0}
        run: |
          python -c "import sys;print(sys.version)"
          micromamba info 
          micromamba list
          cp README.md content
          yarn add @jupyter-widgets/jupyterlab-manager
          yarn add jupyterlab_toastify
          yarn add @krassowski/jupyterlab-lsp
          yarn add @mangroup/jupyterlab-autoplot-display
          jupyter lite build --contents content --output-dir dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
